### ISSUE TITLE
mac clipboard problem

### ISSUE THREAD

**Issue by rorycl** [rorycl/cexfind#1]
The clipboard component fails on an M1 Macbook with:

```
console-darwin-arm64 ; exit;
panic: clipboard: cannot use when CGO_ENABLED=0

goroutine 1 [running]:
golang.design/x/clipboard.initialize(...)
        <path>go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard_nocgo.go:9
golang.design/x/clipboard.Init.func1()
        <path>go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard.go:107 +0x30
sync.(*Once).doSlow(0x1400021c201?, 0x140001aa200?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.design/x/clipboard.Init()
        <path>go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard.go:106 +0x40
main.NewModel()
        <path>src/cexfind/cmd/console/model.go:113 +0x274
main.main()
        <path>src/cexfind/cmd/console/main.go:25 +0x124
logout
```

**Comment by rorycl** [comment]
Fixed in https://github.com/rorycl/cexfind/commit/501f93a271c25976f7619e6a58e3be49a6ca9b7b

**Comment by rorycl** [comment]
Closed.
